// REDVYR KINGDOMS - PHASE 1
// Goal: simple movement, collision, interaction, gold, and local save.

const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");
const startScreen=document.getElementById("startScreen"),gameScreen=document.getElementById("gameScreen"),startBtn=document.getElementById("startBtn"),backBtn=document.getElementById("backBtn");
const nameInput=document.getElementById("nameInput"),worldSelect=document.getElementById("worldSelect"),hudName=document.getElementById("hudName"),hudWorld=document.getElementById("hudWorld"),goldText=document.getElementById("goldText"),promptBox=document.getElementById("prompt");
canvas.width=960;canvas.height=540;
const keys=new Set(),saveKey="redvyr_phase1_save";
let player={x:480,y:330,w:34,h:46,speed:2.8,gold:0,name:"Guest Hero",world:"World A - Main Realm",facing:"down",moving:false,walkTime:0};
const camera={x:0,y:0},world={width:1600,height:1000,tile:32};
const obstacles=[{x:260,y:220,w:120,h:80,type:"tree"},{x:410,y:205,w:70,h:60,type:"rock"},{x:980,y:250,w:150,h:110,type:"house"},{x:1160,y:620,w:220,h:70,type:"wall"},{x:180,y:660,w:130,h:90,type:"trees"},{x:720,y:760,w:140,h:80,type:"rocks"}];
const interactables=[{id:"chest1",x:660,y:360,w:52,h:38,type:"chest",label:"Open Chest",gold:25,used:false},{id:"tree1",x:520,y:610,w:54,h:70,type:"treeNode",label:"Gather Wood",gold:5,used:false},{id:"camp1",x:880,y:500,w:60,h:54,type:"campfire",label:"Warm Camp",gold:10,used:false}];
function loadSave(){const raw=localStorage.getItem(saveKey);if(!raw)return;try{const data=JSON.parse(raw);player.name=data.name||player.name;player.world=data.world||player.world;player.gold=Number(data.gold||0);nameInput.value=player.name;worldSelect.value=player.world}catch{}}
function saveGame(){localStorage.setItem(saveKey,JSON.stringify({name:player.name,world:player.world,gold:player.gold}))}
function startGame(){player.name=nameInput.value.trim()||"Guest Hero";player.world=worldSelect.value;hudName.textContent=player.name;hudWorld.textContent=player.world;goldText.textContent=player.gold;saveGame();startScreen.classList.add("hidden");gameScreen.classList.remove("hidden")}
function backToStart(){gameScreen.classList.add("hidden");startScreen.classList.remove("hidden");saveGame()}
startBtn.addEventListener("click",startGame);backBtn.addEventListener("click",backToStart);
window.addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==="e")tryInteract()});
window.addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
function rectsOverlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function getPlayerHitbox(x=player.x,y=player.y){return{x:x-14,y:y-5,w:28,h:34}}
function canMoveTo(nextX,nextY){const hitbox=getPlayerHitbox(nextX,nextY);if(hitbox.x<0||hitbox.y<0||hitbox.x+hitbox.w>world.width||hitbox.y+hitbox.h>world.height)return false;for(const o of obstacles)if(rectsOverlap(hitbox,o))return false;return true}
function update(){let dx=0,dy=0;if(keys.has("w")||keys.has("arrowup"))dy-=1;if(keys.has("s")||keys.has("arrowdown"))dy+=1;if(keys.has("a")||keys.has("arrowleft"))dx-=1;if(keys.has("d")||keys.has("arrowright"))dx+=1;player.moving=dx!==0||dy!==0;if(player.moving){const len=Math.hypot(dx,dy)||1;dx=dx/len*player.speed;dy=dy/len*player.speed;if(Math.abs(dx)>Math.abs(dy))player.facing=dx>0?"right":"left";else player.facing=dy>0?"down":"up";if(canMoveTo(player.x+dx,player.y))player.x+=dx;if(canMoveTo(player.x,player.y+dy))player.y+=dy;player.walkTime+=.16}camera.x=clamp(player.x-canvas.width/2,0,world.width-canvas.width);camera.y=clamp(player.y-canvas.height/2,0,world.height-canvas.height);const nearby=getNearbyInteractable();promptBox.classList.toggle("hidden",!nearby);if(nearby)promptBox.textContent="Press E to "+nearby.label}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function getNearbyInteractable(){const range={x:player.x-46,y:player.y-46,w:92,h:92};return interactables.find(item=>!item.used&&rectsOverlap(range,item))}
function tryInteract(){if(gameScreen.classList.contains("hidden"))return;const item=getNearbyInteractable();if(!item)return;item.used=true;player.gold+=item.gold;goldText.textContent=player.gold;saveGame();showPrompt("+"+item.gold+" gold")}
function showPrompt(message){promptBox.textContent=message;promptBox.classList.remove("hidden");setTimeout(()=>promptBox.classList.add("hidden"),900)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-camera.x,-camera.y);drawGround();drawPath();drawInteractables();drawObstacles();drawPlayer();drawNameTag();ctx.restore()}
function drawGround(){ctx.fillStyle="#4f9a3e";ctx.fillRect(0,0,world.width,world.height);for(let y=0;y<world.height;y+=world.tile){for(let x=0;x<world.width;x+=world.tile){const alt=(x/world.tile+y/world.tile)%2===0;ctx.fillStyle=alt?"#55a844":"#4b913a";ctx.fillRect(x,y,world.tile,world.tile);if((x*13+y*7)%5===0){ctx.fillStyle="#6fbe55";ctx.fillRect(x+8,y+10,4,4)}}}}
function drawPath(){ctx.fillStyle="#b98955";ctx.beginPath();ctx.moveTo(0,420);ctx.bezierCurveTo(380,330,600,490,880,390);ctx.bezierCurveTo(1120,310,1330,400,1600,300);ctx.lineTo(1600,440);ctx.bezierCurveTo(1300,530,1100,450,880,535);ctx.bezierCurveTo(620,620,390,470,0,560);ctx.closePath();ctx.fill();ctx.fillStyle="rgba(80,45,25,.22)";for(let i=0;i<80;i++){const x=i*83%world.width,y=410+Math.sin(i)*45+(i*37%95);ctx.fillRect(x,y,26,8)}}
function drawObstacles(){for(const o of obstacles){if(o.type.includes("tree"))drawTree(o.x,o.y,o.w,o.h);else if(o.type.includes("rock"))drawRock(o.x,o.y,o.w,o.h);else if(o.type==="house")drawHouse(o.x,o.y,o.w,o.h);else drawWall(o.x,o.y,o.w,o.h)}}
function drawInteractables(){for(const item of interactables){if(item.used)continue;if(item.type==="chest")drawChest(item.x,item.y,item.w,item.h);if(item.type==="treeNode")drawSmallTree(item.x,item.y,item.w,item.h);if(item.type==="campfire")drawCampfire(item.x,item.y,item.w,item.h)}}
function drawTree(x,y,w,h){ctx.fillStyle="#4b2a14";ctx.fillRect(x+w*.42,y+h*.48,w*.16,h*.52);ctx.fillStyle="#235c28";ctx.fillRect(x+w*.10,y+h*.08,w*.80,h*.52);ctx.fillStyle="#2f7832";ctx.fillRect(x+w*.22,y,w*.58,h*.45);ctx.fillStyle="#18451f";ctx.fillRect(x+w*.28,y+h*.22,w*.54,h*.26)}
function drawSmallTree(x,y,w,h){ctx.fillStyle="#4b2a14";ctx.fillRect(x+22,y+35,10,30);ctx.fillStyle="#2f7832";ctx.fillRect(x+8,y+8,38,34);ctx.fillStyle="#235c28";ctx.fillRect(x+16,y,30,32)}
function drawRock(x,y,w,h){ctx.fillStyle="#6a6a62";ctx.fillRect(x+5,y+18,w-10,h-22);ctx.fillStyle="#85857b";ctx.fillRect(x+18,y+8,w-34,h-20);ctx.fillStyle="#4c4c47";ctx.fillRect(x+12,y+h-18,w-22,12)}
function drawHouse(x,y,w,h){ctx.fillStyle="#7a3d1a";ctx.fillRect(x,y+35,w,h-35);ctx.fillStyle="#c24a28";ctx.beginPath();ctx.moveTo(x-10,y+40);ctx.lineTo(x+w/2,y);ctx.lineTo(x+w+10,y+40);ctx.closePath();ctx.fill();ctx.fillStyle="#3a1b0c";ctx.fillRect(x+w*.42,y+h-44,w*.18,44);ctx.fillStyle="#ffd37a";ctx.fillRect(x+18,y+55,24,24)}
function drawWall(x,y,w,h){ctx.fillStyle="#8b7655";ctx.fillRect(x,y,w,h);ctx.fillStyle="#6b5a40";for(let i=0;i<w;i+=38){ctx.fillRect(x+i,y+10,28,12);ctx.fillRect(x+i+14,y+42,28,12)}}
function drawChest(x,y,w,h){ctx.fillStyle="#7a3d1a";ctx.fillRect(x,y+12,w,h-12);ctx.fillStyle="#b85d24";ctx.fillRect(x,y,w,18);ctx.fillStyle="#f2c35f";ctx.fillRect(x+w/2-5,y+14,10,14)}
function drawCampfire(x,y,w,h){ctx.fillStyle="#4b2a14";ctx.fillRect(x+8,y+38,44,10);ctx.fillStyle="#ff9b22";ctx.fillRect(x+22,y+16,18,24);ctx.fillStyle="#ffd15c";ctx.fillRect(x+27,y+8,8,24)}
function drawPlayer(){const x=player.x,y=player.y,step=player.moving?Math.sin(player.walkTime):0,legOffset=step>0?3:-3;ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(x-22,y+25,44,10);ctx.fillStyle="#7c1a14";ctx.fillRect(x-26,y-5,18,50);ctx.fillStyle="#3b1c0c";ctx.fillRect(x-13,y+24+legOffset,10,26);ctx.fillRect(x+5,y+24-legOffset,10,26);ctx.fillStyle="#7a3519";ctx.fillRect(x-16,y+47+legOffset,15,8);ctx.fillRect(x+4,y+47-legOffset,15,8);ctx.fillStyle="#9f1f17";ctx.fillRect(x-19,y-10,38,38);ctx.fillStyle="#5b2a12";ctx.fillRect(x-20,y+13,40,6);ctx.fillStyle="#f2c35f";ctx.fillRect(x-4,y+11,8,10);ctx.fillStyle="#f7c99a";ctx.fillRect(x-18,y-44,36,34);ctx.fillStyle="#7c3518";ctx.fillRect(x-22,y-52,44,16);ctx.fillRect(x-14,y-60,20,12);ctx.fillStyle="#4a1f0f";ctx.fillRect(x-20,y-36,7,25);ctx.fillRect(x+13,y-36,7,25);ctx.fillStyle="#33150a";if(player.facing==="up"){ctx.fillRect(x-12,y-39,8,6);ctx.fillRect(x+4,y-39,8,6)}else if(player.facing==="left"){ctx.fillRect(x-12,y-34,7,10)}else if(player.facing==="right"){ctx.fillRect(x+5,y-34,7,10)}else{ctx.fillRect(x-11,y-34,7,11);ctx.fillRect(x+5,y-34,7,11);ctx.fillStyle="#8e1c13";ctx.fillRect(x-5,y-20,10,4)}}
function drawNameTag(){const text=player.name;ctx.font="bold 13px Arial";const width=ctx.measureText(text).width+18,x=player.x-width/2,y=player.y-82;ctx.fillStyle="rgba(22,11,5,.78)";ctx.fillRect(x,y,width,22);ctx.strokeStyle="#f2c35f";ctx.strokeRect(x,y,width,22);ctx.fillStyle="#ffe4a6";ctx.fillText(text,x+9,y+15)}
function gameLoop(){update();draw();requestAnimationFrame(gameLoop)}
loadSave();gameLoop();
